version: "3.9"

services:
  backend:
    build:
      context: ./backend
    command: python devwatch.py
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      RUNNING_IN_DOCKER: "True"
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: freelancequestdb
      POSTGRES_USER: freelanceadmin
      POSTGRES_PASSWORD: testpassword123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7

volumes:
  postgres_data:

