# Generated by Django 5.2 on 2025-04-22 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0002_gig_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='status',
            field=models.CharField(choices=[('available', 'Laisvas'), ('pending', 'Laukiama patvirtinimo'), ('in_progress', 'Vykdomas'), ('completed', 'Įvykdytas'), ('cancelled', 'Atšauktas')], default='available', max_length=20),
        ),
    ]
