# Generated by Django 5.2 on 2025-05-02 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0004_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='GigSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='submissions/')),
                ('message', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('gig', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='gigs.gig')),
            ],
        ),
    ]
