# Generated by Django 5.2 on 2025-05-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0006_gig_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='status',
            field=models.CharField(choices=[('available', 'Laisvas'), ('pending', 'Laukiama patvirtinimo'), ('in_progress', 'Vykdomas'), ('submitted', 'Pateiktas'), ('completed', 'Įvykdytas'), ('cancelled', 'Atšauktas')], default='available', max_length=20),
        ),
    ]
