# Generated by Django 5.2 on 2025-05-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0007_alter_gig_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='status',
            field=models.CharField(choices=[('available', 'Laisvas'), ('in_progress', 'Vykdomas'), ('pending', 'Laukiama patvirtinimo'), ('completed', 'Įvykdytas'), ('cancelled', 'Atšauktas')], default='available', max_length=20),
        ),
    ]
