# Generated by Django 5.2 on 2025-05-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0008_alter_gig_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
