# Generated by Django 5.2 on 2025-05-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_alter_gamificationprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('cost', models.PositiveIntegerField()),
                ('effect_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='gamificationprofile',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mission',
            name='point_reward',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
