# Generated by Django 5.2 on 2025-05-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0006_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='code',
            field=models.CharField(default='temp_code', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mission',
            name='code',
            field=models.CharField(default='temp_code', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
