# Generated by Django 5.2 on 2025-05-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0007_badge_code_mission_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermissionprogress',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
