# Generated by Django 5.2 on 2025-05-06 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0008_usermissionprogress_seen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
