# Generated by Django 5.2 on 2025-05-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0009_delete_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='goal_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mission',
            name='track_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
