# Generated by Django 5.2 on 2025-05-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0010_mission_goal_count_mission_track_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermissionprogress',
            name='current_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
