# Generated by Django 5.2 on 2025-05-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0011_usermissionprogress_current_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermissionprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
