# Generated by Django 5.2 on 2025-04-19 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='xp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
