# Generated by Django 5.2 on 2025-04-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_freelancerprofile_xp_remove_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.SlugField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
